name: Deploy to Google App Engine

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install 

    - name: Set up Google Cloud Platform
      uses: google-github-actions/setup-gcloud@v0.8.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate GCP account
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json

    - name: Check gcloud auth list
      run: gcloud auth list

    - name: Deploy to App Engine
      run: gcloud app deploy --quiet --project ${{ secrets.GCP_PROJECT_ID }}
      env:
        CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
